### PR TITLE
Resize Images Correctly on Mobile (web)

### PR DESCRIPTION
**Pull request by maaslalani**
### Changes
- Add `<picture>` and `<source>` for media

### CODE REVIEW

**Comment by maaslalani** [comment]
@lpmi-13 FWIW, I think I found the solution https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/

**Comment by lpmi-13** [comment]
Ah yes, of course! The picture element. I had totally used this in "regular" Web frontends and totally forgot about it. Magic!

Screenshot from that branch on my phone

Screenshot_20220805-070605_Chrome

**Comment by maaslalani** [comment]
Yeah, I can't believe I found it somehow!

**Comment by maaslalani** [comment]
Works like a Charm™

**Pull request merged**
