### PR TITLE
Confirmation Default

### LINKED ISSUE #31: gum confirm should have a default option
Similar to [#29] gum confirm should have an option that tells gum whether to default to `Yes` (affirmative) or `No` (negative).

### PR DESCRIPTION
**Pull request by maaslalani**
Fixes #31 

```
gum confirm --default=false
```

### CODE REVIEW

**Review by TimDev9492 — CHANGES_REQUESTED** [review]
I think you accidentally deleted the option to press the right arrow key when selecting an option in `gum confirm`

**Comment by maaslalani** [comment]
> I think you accidentally deleted the option to press the right arrow key when selecting an option in `gum confirm`

It is there, I believe, at least it works for me still:
> "right", "l", "ctrl+n", "shift+tab"

**Comment by TimDev9492** [comment]
Right, I just missed something in the code! Everything's fine, sorry.

**Comment by maaslalani** [comment]
Awesome! I will merge this 🙂 Thank you for the feature suggestion

**Pull request merged**
