### PR TITLE
Fix #31 (add flag to set negative option as default `gum confirm`)

### LINKED ISSUE #31: gum confirm should have a default option
Similar to [#29] gum confirm should have an option that tells gum whether to default to `Yes` (affirmative) or `No` (negative).

### PR DESCRIPTION
**Pull request by TimDev9492**
I don't know if I missed anything. Functionality-wise, it works!

### CODE REVIEW

**Comment by maaslalani** [comment]
Hey I did a bit of a refactoring in #36, let me know if the following is reasonable for you since I think it makes the code a bit cleaner and the logic a bit easier to understand:

```
gum confirm --default=false
```

**Comment by TimDev9492** [comment]
I think you broke something in #36 but the refactoring looks good to me. I'd be completely fine with this change!

**Comment by TimDev9492** [comment]
Nevermind

**Comment by maaslalani** [comment]
Superseded by: https://github.com/charmbracelet/gum/pull/36

**Pull request closed without merging**
