### PR TITLE
fix(pager): use help bubble

### PR DESCRIPTION
**Pull request by caarlos0**
use the help bubble in the pager component

### CODE REVIEW

**Review by aymanbagabas — APPROVED** [review]

**Review by bashbunni — APPROVED** [review]
before:
image

after:
image

**Comment by bashbunni** [comment]
didn't look at why lint is failing though 🤔

**Comment by caarlos0** [comment]
> didn't look at why lint is failing though 🤔

was fixed in previous PRs I think

**Comment by caarlos0** [comment]
> before: image
> 
> after: image

yup, only change was to make the help lowercase, so it matches with the other components as well

**Pull request merged**
