### PR TITLE
Use responsive width

### PR DESCRIPTION
**Pull request by lpmi-13**
Fixed size of terminals was making the mobile view formatting look off.

### CODE REVIEW

**Comment by lpmi-13** [comment]
Current view on mobile

Screenshot_20220801-094628_Chrome

Mobile view with proposed commit

Screenshot_20220801-094735_Chrome

**Comment by maaslalani** [comment]
Hi! This is great but unfortunately there is no way to specify a `max-width` (at least from what I tried) so the images / GIFs don't look good on desktop. If you know a way to add a max-width and keep the width 100%. Please do let me know!

**Comment by lpmi-13** [comment]
ah right, okay...I feel like I had to deal with that in a previous project. Lemme do some digging and I'll see what I can come up with.

**Comment by maaslalani** [comment]
@lpmi-13 I tried similar things as well, looks like inline-styles don't work due to security reasons:

> The HTML is sanitized, aggressively removing things that could harm you and your kin—such as script tags, inline-styles, and class or id attributes.


https://github.com/github/markup#github-markup

**Comment by lpmi-13** [comment]
Haha, yeah fair enough. I'll go ahead and close this. Fantastic work with this project by the way, gonna see if I can convince my team to start using it!

**Comment by maaslalani** [comment]
Thanks @lpmi-13, really appreciate the PR and you using the tool ❤️

**Comment by maaslalani** [comment]
Please do open issues / let me know if there's anything missing or that you wish was in the tool 🙂

**Pull request closed without merging**
