### PR TITLE
feat(filter): allow to pre-select items with --selected

### LINKED ISSUE #593: Add preselected options when using filter command
**Is your feature request related to a problem? Please describe.**
I'm using gum to let the user to select from a list of options with some of them are defaults.
To ease the selection, I need to have a list of preselected options using filter command.

**Describe the solution you'd like**
Add `--selected` flag when using `gum filter` command to preselect options.

**Describe alternatives you've considered**
No alternative found yet.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by caarlos0**
closes #593

### CODE REVIEW

**Comment by bashbunni** [comment]
Hey just tried this with the following options on `main` and didn't get the expected result. In both cases, the filtered results are all unselected

```
# Select js
platforms=$(echo "js|android|ios" | gum filter --input-delimiter="|" --no-limit --output-delimiter=",") --selected="js"

# Select all
platforms=$(echo "js|android|ios" | gum filter --input-delimiter="|" --no-limit --output-delimiter=",") --selected="*"

# This one worked
echo "Applications\nLibrary\nDownloads" | gum filter --selected="Downloads"
```
My guess is it's not working when there is a `--no-limit` flag on the filter command.

**Comment by caarlos0** [comment]
> Hey just tried this with the following options on `main` and didn't get the expected result. In both cases, the filtered results are all unselected
> 
> ```
> # Select js
> platforms=$(echo "js|android|ios" | gum filter --input-delimiter="|" --no-limit --output-delimiter=",") --selected="js"
> 
> # Select all
> platforms=$(echo "js|android|ios" | gum filter --input-delimiter="|" --no-limit --output-delimiter=",") --selected="*"
> 
> # This one worked
> echo "Applications\nLibrary\nDownloads" | gum filter --selected="Downloads"
> ```
> 
> My guess is it's not working when there is a `--no-limit` flag on the filter command.

the `--selected` flag is outside the `()`:

```sh
# Select js
platforms=$(echo "js|android|ios" | gum filter --input-delimiter="|" --no-limit --output-delimiter="," --selected="js")

# Select all
platforms=$(echo "js|android|ios" | gum filter --input-delimiter="|" --no-limit --output-delimiter="," --selected="*")

# This one worked
echo "Applications\nLibrary\nDownloads" | gum filter --selected="Downloads"
```

**Comment by bashbunni** [comment]
LOL @caarlos0 thank you for catching that! 🙏

**Comment by bashbunni** [comment]
merp, for some reason `--selected=*` isn't working anymore :/ tried your working example again just to confirm the example in the release notes would work, but for some reason it's not selecting all of the elements by default when it opens the filter view

`echo "js|android|ios" | gum filter --input-delimiter="|" --no-limit --output-delimiter="," --selected="*"`
image

**Comment by caarlos0** [comment]
ouch, true, also just noticed that tab on the last item is broken

**Comment by caarlos0** [comment]
fixed on main

**Pull request merged**
